### PR TITLE
Feature/support swift package manager

### PR DESCRIPTION
**Pull request by andrewreeman**
Same pull request as in the Marc Balwin's [original project](https://github.com/marcbaldwin/GestureRecognizerClosures/pull/23)

### CODE REVIEW

**Review by lawmaestro — CHANGES_REQUESTED** [review]
I've just tested this out and it looks great, thanks! Would you mind just adding a snippet to the readme to note the SPM installation option? Something like:

```
### Using Swift Package Manager

To install using [Swift Package Manager](https://github.com/apple/swift-package-manager) you can follow the [tutorial published by Apple](https://developer.apple.com/documentation/xcode/adding_package_dependencies_to_your_app) using the URL for the GestureRecognizerClosures repo with the current version:

1. In Xcode, select “File” → “Add Packages...”
2. Enter https://github.com/lawmaestro/GestureRecognizerClosures.git
```

**Comment by andrewreeman** [comment]
Ok good idea! I'll add that shortly and will also add a section about using it in a library too, like on this [PromiseKit page](https://github.com/mxcl/PromiseKit/blob/master/Documentation/Installation.md#swiftpm)

**Comment by lawmaestro** [comment]
Awesome, thanks @andrewreeman 🙌

**Comment by andrewreeman** [comment]
@lawmaestro how does this look? You can preview the README using the [github code editor](https://docs.github.com/en/codespaces/the-githubdev-web-based-editor)

**Comment by lawmaestro** [comment]
This looks great @andrewreeman, thanks! I'll go ahead and merge

**Comment by lawmaestro** [comment]
I'll add new version tags and update the change log shortly

**Pull request merged**
